### ISSUE TITLE
[Enhancement] Make the email at the end of the home page an hyperlink

### ISSUE THREAD

**Issue by yannis300307** [CoCoSol007/my-website#1]
The "contact@cocosol.fr" email at the end of the home page sould be a mailto link.
```html
<a href="mailto://contact@cocosol.fr">contact@cocosol.fr</a>
```

**Comment by CoCoSol007** [comment]
Fix on [commit 85](https://github.com/CoCoSol007/my-website/commit/d531db4253edd27c2f016ed007394dabe48bc1ca).
